[package]
name = "edgeone"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
proxy-wasm = "0.2"
log = "*"
hex = "0.4"
hmac = "0.12"
lru = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
time = "0.3"
